### PR TITLE
Update for special edition - Best of a bad year

### PR DESCRIPTION
**Pull request by blishen**
## What's changed?
We've updated colours and an icon

### CODE REVIEW

**Comment by philmcmahon** [comment]
This has been  tested on CODE

**Review by jonathonherbert — APPROVED** [review]
LGTM! Trying to decipher that image, and I attempted to blow it up a bit but of course the signature is invalid ... as an aside, how do you create a fastly image signature?

**Comment by philmcmahon** [comment]
@jonathonherbert http://image-url-signer.s3-website-eu-west-1.amazonaws.com/ is your friend though it's only accessible over VPN (and hasn't been added to the DC2 VPN yet!) The signature  itself is pretty stupid: https://github.com/guardian/image-url-signer-lambda/blob/master/lambda_function.py#L23

**Comment by jonathonherbert** [comment]
Amazing, thanks @philmcmahon!

**Pull request merged**
