### PR TITLE
Remove criteria for cutout images

### PR DESCRIPTION
**Pull request by jonathonherbert**
## What's changed?

Remove criteria for cutout images ... they're not there in the old tool! 5x3 and ~6x4~ 6x5 are both valid options, I think (@paperboyo?), and in the absence of being able to check for both at once let's revert to the old behaviour.

### General
- [ ] 🤖 Relevant tests added
- [x] ✅ CI checks / tests run locally
- [ ] 🔍 Checked on CODE

### Client
- [x] 🚫 No obvious console errors on the client (i.e. React dev mode errors)
- [x] 🎛️ No regressions with existing user interactions (i.e. all existing buttons, inputs etc. work)
- [ ] 📷 Screenshots / GIFs of relevant UI changes included

### CODE REVIEW

**Comment by paperboyo** [comment]
> 6x4

5/5, but yeah this is all good! Thanks!

**Comment by jonathonherbert** [comment]
haha @paperboyo glad I asked! 👍

**Comment by RichieAHB** [comment]
Where did image criteria come from if not the old tool, out of interest?

**Comment by paperboyo** [comment]
> Where did image criteria come from if not the old tool, out of interest?

Probably projected from trailpics (that came from the old tool) to cutouts by mistake.

**Comment by jonathonherbert** [comment]
@RichieAHB -- @paperboyo is correct, I mistakenly included the same criteria for both image types.

**Pull request merged**
