### PR TITLE
Fix a race condition

### PR DESCRIPTION
**Pull request by piuccio**
maybe

@janua

### CODE REVIEW

**Comment by janua** [comment]
This won't fix the race condition if it's a race condition...

**Comment by piuccio** [comment]
it won't fix two users writing at the same time but it prevents the same user from issuing another request until the previous put is complete.

maybe 😁

**Comment by janua** [comment]
Seeing as this is synchronous anyway, it probably is waiting already even without the return type.

**Comment by piuccio** [comment]
ok this new update should really solve it. While a request is on progress we apply a `pending` class on the collection, this prevents user actions such as adding another story. However the class is not applied on the publish/discard buttons so it's possible to publish before the previous edit completes.

**Pull request merged**
