### PR TITLE
Add Video Container Type

### PR DESCRIPTION
**Pull request by sammorrisdesign**
Adding to the tool to start work on frontend. Is there anything else I need to do to add it?

### CODE REVIEW

**Comment by piuccio** [comment]
:+1:

Do you need it in the behemoth container?

**Comment by sammorrisdesign** [comment]
@piuccio No the behemoth container is a collection of all slices, not containers. At the moment it is anyway.

**Comment by piuccio** [comment]
Honestly I don't remember, but I think it is. 

If it compiles it shouldn't do any harm to merge. You can deploy your branch on CODE, if you can see the thumbnail in the config tool than it's all good.

**Comment by piuccio** [comment]
ok to deploy?

**Comment by sammorrisdesign** [comment]
Do it @piuccio

**Pull request merged**
