### PR TITLE
First stab at the next special edition

### PR DESCRIPTION
**Pull request by blishen**
We don't know the swatches yet, the colours for the headers and text, the icon etc. This is a start for 10, this will be further modified before launch, once we have some more details. NB the huge amount of fronts is to cover us for the fact that we won't know until late in the day, what the ordering of swatches applied to fronts will.

## What's changed?
New edition template.

## Implementation notes
Edited by a product manager in Github. Beware linting and usual nonsense.

## Checklist
Nothing checked.

### CODE REVIEW

**Comment by aug24** [comment]
You're going to need to add stuff to another file before this does anything, yes?

**Review by aug24 — CHANGES_REQUESTED** [review]
Need to add edition to list of editions per the instructions to make it have any effect at all.

**Comment by philmcmahon** [comment]
Need to add it here:
https://github.com/guardian/facia-tool/blob/00155711665a9fe9c325bc7609f868bd8a0ebd11/app/model/editions/EditionsTemplates.scala#L21

and here:
https://github.com/guardian/facia-tool/blob/00155711665a9fe9c325bc7609f868bd8a0ebd11/app/model/editions/EditionsTemplates.scala#L70

I suggest just replacing EditionEarth from those lists

**Comment by blishen** [comment]
Made changes that Pip requested, and updated the branch to main.

**Review by philmcmahon — APPROVED** [review]
LGTM

**Pull request merged**
