### PR TITLE
Correct position of Publish button second pass

### PR DESCRIPTION
**Pull request by JustinPinner**
## What's changed?
This PR builds on Rachel's [#1640](https://github.com/guardian/facia-tool/pull/1640), but as it's my first time trying to mess with UI components in this project I thought I'd do it on a sub-branch in case I made things worse.

Taking Jon's comments from [#1640](https://github.com/guardian/facia-tool/pull/1640) into consideration I've adjusted a couple of things to a) restore the Check button and make it (very nearly) the same size as the Publish button and b) push the `Send us feedback` link back to the left hand section of its container.

I've run the basic `sbt test` and V2's `fronts-client` `yarn test` which all passed. And _it worked in my browser_ 😁 

### Feast edition behaviour
Screen Recording 2024-09-06 at 15 11 02

---
### Daily edition behaviour
Screen Recording 2024-09-06 at 15 09 19

---
### Regular front behaviour
Screen Recording 2024-09-06 at 15 15 08

---

## Implementation notes
You'll see that the presence of the Check and Publish buttons in the Feast edition view means that the Clipboard area doesn't really recover any screen real estate when it's closed, but unless we move those buttons I'm not sure how to make that better. If anyone uses a relatively low-resolution screen this could be a problem but I believe the clipboard is generally used quite heavily during Feast edition curation.

### General
- [ ] 🤖 Relevant tests added
- [x] ✅ CI checks / tests run locally
- [ ] 🔍 Checked on CODE
- [x] 🔍 Checked locally (CODE has been very busy)

### Client
- [ ] 🚫 No obvious console errors on the client (i.e. React dev mode errors)
- [ ] 🎛️ No regressions with existing user interactions (i.e. all existing buttons, inputs etc. work)
- [ ] 📷 Screenshots / GIFs of relevant UI changes included

### CODE REVIEW

**Comment by Divs-B** [comment]
Slight gap issue between proof and publish buttons when we visit any other edition, I have tried UK daily edition here:

image

_______________


At present CODE looks like :

image

**Review by fredex42 — CHANGES_REQUESTED** [review]
As @Divs-B  indicated 😁

**Comment by JustinPinner** [comment]
Oh my. Not to worry, I think I can fix that! Thanks 😄

**Comment by Divs-B** [comment]
almost there, equal gap might needed between 3 buttons..proof and publish button looks slight with more gap than between check and proof buttons.
image

**Review by Divs-B — APPROVED** [review]
just equal gap to cover otherwise looking good 👍

**Comment by Divs-B** [comment]
> almost there, equal gap might needed between 3 buttons..proof and publish button looks slight with more gap than between check and proof buttons. image

oh it looks fine, i can see equal gap , dont know why it wasnt clear in before screen
image

**Comment by Divs-B** [comment]
> just equal gap to cover otherwise looking good 👍

good to go 👍

**Comment by JustinPinner** [comment]
> oh it looks fine, i can see equal gap , dont know why it wasnt clear in before screen image

I think this is when the button is clicked it gets a bit bigger or has a focus box around it or something. Figured we could fine tune it later if it's really an issue?

**Comment by codingWithRach** [comment]
Looks good

**Review by fredex42 — APPROVED** [review]
😁

**Pull request merged**
