### PR TITLE
Ready Feast curation for production

### PR DESCRIPTION
**Pull request by jonathonherbert**
## What's changed?

This PR makes three changes that were necessary to successfully test front publication end-to-end in the Feast app:

- correct front names for CODE
- add a temporary -test suffix for PROD fronts, to ensure that hitting publishing in PROD doesn't overwrite mis-en-place data yet
- add an empty 'body' property to feast collections for the Android app to display collections properly – it's necessary for [their model](https://github.com/guardian/android-feast/blob/6e647b2aec3a84aa22df1b663c7200f0bb30b684/core/model/src/main/kotlin/uk/co/guardian/feast/model/FeastArticle.kt#L11)

Re: front names, this PR has each Feast edition write the correct path name to `recipe-backend` (`FeastNorthernHemisphere` -> `northern`, `FeastSouthernHemisphere` -> `southern`) – with a caveat that at the moment, `PROD` will add the suffix `test` to the edition, to avoid stomping on mis-en-place's data.

Once we're happy, we can then remove the distinction between CODE and PROD.

## Implementation notes

I've added a test for the PROD behaviour, which meant wiring through property overrides into `ApplicationConfiguration` in b92a7992c99ce8763fca74cdd6797b5c5cd33455 to allow us to specify a stage in tests – hope that makes sense.

Other model changes are well covered in other tests.

## How to test

- Deploy the [sister branch in recipes-backend](https://github.com/guardian/recipes-backend/pull/62) to CODE. This includes some small but important model changes.
- Deploy this branch to CODE.
- If you publish a Front for the current day for a given issue, after a short delay, you should see it in the `/curation.json` for the appropriate recipes-backend URL (e.g. `recipes.code.dev-guardianapis.com/northern/all-recipes/curation.json`.)

If you'd like to see a nice full front, use the new [Feast -> Fronts script](https://github.com/guardian/facia-tool/pull/1645) to populate CODE issues with PROD data.

Tested end-to-end in CODE with the Feast app (Android):

|Recipes|Chefs and collections|
|-|-|
|||

### General
- [x] 🤖 Relevant tests added
- [x] ✅ CI checks / tests run locally
- [x] 🔍 Checked on CODE

### Client
- [ ] 🚫 No obvious console errors on the client (i.e. React dev mode errors)
- [ ] 🎛️ No regressions with existing user interactions (i.e. all existing buttons, inputs etc. work)
- [x] 📷 Screenshots / GIFs of relevant UI changes included

### CODE REVIEW

**Comment by Divs-B** [comment]
Tested on my android device after publishing issue for today, i can see content of the issue are present on the device.
Happy to approve.

Small (non-blocking) thing to check when I republished same issue after adding two more recipes , I can see data is readily available on my Phone but Notification window in Front doesnt show "Published" after a while too (though i think it is published and data is there on app as well), so need to check this.
image

**Comment by Divs-B** [comment]
As first time testing on device so need to confirm one more thing, how to check Chef cards on the app? 
I have added them on Front but can't see on app side. no issues for recipes as they are available all fine on the app. 
I think I have missed something regarding this, will check with team.

**Comment by jonathonherbert** [comment]
> Tested on my android device after publishing issue for today, i can see content of the issue are present on the device. Happy to approve.
> 
> Small (non-blocking) thing to check when I republished same issue after adding two more recipes , I can see data is readily available on my Phone but Notification window in Front doesnt show "Published" after a while too (though i think it is published and data is there on app as well), so need to check this. 

This may be because someone is running a version of Fronts locally, which will also be polling from the same SQS queue in CODE – and stealing your publish messages! I'd say worth double checking that you or others on the team aren't running Fronts and trying again.

**Comment by Divs-B** [comment]
> > Small (non-blocking) thing to check when I republished same issue after adding two more recipes , I can see data is readily available on my Phone but Notification window in Front doesnt show "Published" after a while too ......
> 
> This may be because someone is running a version of Fronts locally, which will also be polling from the same SQS queue in CODE – and stealing your publish messages! I'd say worth double checking that you or others on the team aren't running Fronts and trying again.

Thanks @jonathonherbert for quick check on this (even on your leave), 
yes we think thats what the case , team checked on it,
now publishing looks all fine , did few times:

image

**Comment by Divs-B** [comment]
> As first time testing on device so need to confirm one more thing, how to check Chef cards on the app? I have added them on Front but can't see on app side. no issues for recipes as they are available all fine on the app. I think I have missed something regarding this, will check with team.

@fredex42 also tested at his end, we can see `meat-free` not showing chefs container at all, 
though curation.json looks fine. 
@fredex42 posted to Apps Devs to verify this.

**Comment by Divs-B** [comment]
We are on continuing testing on this, recent report on Android device testing: 
- Tested working of script from MEP to FRONT - looking good,
- Published curated data from FRONT to APP - data flow looked good, at App's end we observed discrepancies and hence reported issues app developers like missing recipes and chefs.

@michaelclapham from Android team has fixed around taken-down logic, we tested on his given new build version of the android app and found that the data looking in much better state. All recipes are available, 2 of them were missed in comparison of FRONT but then we found those recipes were taken down. so all fine here for recipes.

We have 1 missing chef issue, @michaelclapham done fix for that and we will test on new build for chefs too.
nearly at the end for Android. We will look more in iOS too then will good to go ahead.

details are getting logged in for refernce for us at https://trello.com/c/vag8ixIi/3211-ensure-that-in-code-we-publish-to-the-relevant-fronts

**Pull request merged**
